name: qr_scanner
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^0.1.1
  syncfusion_flutter_xlsio: ^19.1.64-beta
  file_saver: ^0.1.0
  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

